--    a. Script DDL para criar as tabelas do BD de pedidos: CLIENTE, PF, PJ, PRODUTO, FONE_CLIENTE,
--       FONE_VENEDOR, PRATELEIRA e VENDEDOR. Colocar as regras de integridade no script de criação.
-- SOLUÇÃO:
CREATE TABLE CLIENTE (
CODIGO INTEGER CONSTRAINT PK_CLIENTE PRIMARY KEY,
NOME varchar2(60) not null,
RUA varchar2(80) not null,
NR NUMBER(4) not null,
BAIRRO varchar2(50) not null,
COMPLEMENTO varchar2(100),
CIDADE varchar2(50) not null,
UF varchar2(2) not null,
CEP varchar2(10) not null
);


CREATE TABLE PF (
CODIGO_CLI INTEGER CONSTRAINT PK_CLIENTE_PF PRIMARY KEY,
CPF varchar2(14) not null,
RG varchar2(10) not null,
DATA_NASCIMENTO DATE not null,
CONSTRAINT FK_PF_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO)
);


CREATE TABLE PJ (
CODIGO_CLI INTEGER,
CNPJ varchar2(19) not null,
IE varchar2(10) not null,
NOME_FANTASIA varchar2(60) not null,
CONSTRAINT PK_CLIENTE_PJ PRIMARY KEY (CODIGO_CLI),
CONSTRAINT FK_PJ_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE(CODIGO)
);


CREATE TABLE PRODUTO (
CODIGO INT CONSTRAINT PK_PRODUTO PRIMARY KEY,
DESCRICAO VARCHAR2(80) NOT NULL,
UNID_MEDIDA VARCHAR2(10) NOT NULL
);


CREATE TABLE FONE_CLIENTE (
NUMERO varchar2(14),
CODIGO_CLI INTEGER,
CONSTRAINT PK_FONE_CLIENTE PRIMARY KEY (NUMERO, CODIGO_CLI),
CONSTRAINT FK_FONE_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO)
);


CREATE TABLE FONE_VENDEDOR (
NUMERO varchar2(14),
MATRICULA_VEN INTEGER,
CONSTRAINT PK_FONE_VENDEDOR PRIMARY KEY (NUMERO, MATRICULA_VEN),
CONSTRAINT FK_FONE_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR (MATRICULA)
);


CREATE TABLE PRATELEIRA (
CODIGO NUMBER(3),
DESCRICAO VARCHAR2(50) NOT NULL,
NUMERO_SECOES NUMBER(2) NOT NULL,
CONSTRAINT PK_PRATELEIRA PRIMARY KEY (CODIGO)
);


CREATE TABLE VENDEDOR (
MATRICULA INTEGER,
NOME VARCHAR2(60) NOT NULL,
CPF VARCHAR2(14) NOT NULL,
CONSTRAINT PK_VENDEDOR PRIMARY KEY (MATRICULA)
);