b. Criar as tabelas associativas: PEDIDO, ESTOQUE, CAPACIDADE_ESTOQUE E ITEM_PRODUTO.  
--       Não incluir na criação dessas tabelas as chaves primária (PK) e estrangeiras (FK).
-- SOLUÇÃO:
CREATE TABLE PEDIDO (
NUMERO NUMBER(6) NOT NULL,
DATA DATE NOT NULL,
PRAZO_ENTREGA DATE,
RUA VARCHAR2(80),
NR NUMBER(4),
BAIRRO VARCHAR2(50),
COMPLEMENTO VARCHAR2(100),
CIDADE VARCHAR2(50),
UF VARCHAR2(2),
CEP VARCHAR2(10),
TOTAL_FATURA NUMBER(8,2),
CODIGO_CLI INTEGER NOT NULL,
MATRICULA_VEN INTEGER NOT NULL
);

CREATE TABLE ESTOQUE (
DATA_ENTREGA DATE NOT NULL,
CODIGO_PRO INTEGER NOT NULL,
CODIGO_PRA NUMBER(3) NOT NULL,
QUANTIDADE NUMBER(5) NOT NULL,
DATA_VALIDADE DATE
);

CREATE TABLE CAPACIDADE_ESTOQUE (
CODIGO_PRO INTEGER NOT NULL,
CODIGO_PRA NUMBER(3) NOT NULL,
QUANTIDADE NUMBER(5) NOT NULL
);

CREATE TABLE ITEM_PRODUTO (
CODIGO_PRO INTEGER NOT NULL,
NUMERO_PED NUMBER(6) NOT NULL,
QUANTIDADE NUMBER(5) NOT NULL,
PRECO_UNITARIO NUMBER(5,2) NOT NULL,
VALOR_ITEM NUMBER(7,2)
);

--    c. Criar as constraints de chave primaria (primary key) para as tabelas associativas.
-- RESOLUÇÃO:
ALTER TABLE PEDIDO
ADD CONSTRAINT PK_PEDIDO PRIMARY KEY (NUMERO);

ALTER TABLE ESTOQUE
ADD CONSTRAINT PK_ESTOQUE PRIMARY KEY (DATA_ENTREGA, CODIGO_PRO, CODIGO_PRA);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT PK_CAPACIDADE_ESTOQUE PRIMARY KEY (CODIGO_PRO, CODIGO_PRA);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT PK_ITEM_PRODUTO PRIMARY KEY (CODIGO_PRO, NUMERO_PED);

--    d. Criar as constraints das chaves estrangeiras (foreing key) para as tabelas associativas.
-- RESOLUÇÃO:

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_CLIENTE FOREIGN KEY (CODIGO_CLI) REFERENCES CLIENTE (CODIGO);

ALTER TABLE PEDIDO
ADD CONSTRAINT FK_PED_VENDEDOR FOREIGN KEY (MATRICULA_VEN) REFERENCES VENDEDOR (MATRICULA);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_EST_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO);

ALTER TABLE ESTOQUE
ADD CONSTRAINT FK_EST_PRATELEIRA FOREIGN KEY (CODIGO_PRA) REFERENCES PRATELEIRA (CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAP_EST_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO);

ALTER TABLE CAPACIDADE_ESTOQUE
ADD CONSTRAINT FK_CAP_EST_PRATELEIRA FOREIGN KEY (CODIGO_PRA) REFERENCES PRATELEIRA (CODIGO);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PRODUTO FOREIGN KEY (CODIGO_PRO) REFERENCES PRODUTO (CODIGO);

ALTER TABLE ITEM_PRODUTO
ADD CONSTRAINT FK_ITEM_PEDIDO FOREIGN KEY (NUMERO_PED) REFERENCES PEDIDO (NUMERO);